#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Action_NormalDash

#include "Basic.hpp"

#include "BP_Action_NormalDash_classes.hpp"
#include "BP_Action_NormalDash_parameters.hpp"


namespace SDK
{

// Function BP_Action_NormalDash.BP_Action_NormalDash_C.ExecuteUbergraph_BP_Action_NormalDash
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Action_NormalDash_C::ExecuteUbergraph_BP_Action_NormalDash(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Action_NormalDash_C", "ExecuteUbergraph_BP_Action_NormalDash");

	Params::BP_Action_NormalDash_C_ExecuteUbergraph_BP_Action_NormalDash Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Action_NormalDash.BP_Action_NormalDash_C.OnStart
// (Event, Public, BlueprintEvent)

void UBP_Action_NormalDash_C::OnStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Action_NormalDash_C", "OnStart");

	UObject::ProcessEvent(Func, nullptr);
}

}

