#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AssultSlash

#include "Basic.hpp"

#include "ProjectP_structs.hpp"
#include "ProjectP_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AssultSlash.BP_AssultSlash_C
// 0x0008 (0x0278 - 0x0270)
class UBP_AssultSlash_C final : public ULAction_MultiAnim
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0270(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_AssultSlash(int32 EntryPoint);
	void OnTick(float DeltaTime);
	void OnCommandOccurred_Event(class ULActMgrComponent* ActMgrComponent, class AActor* TargetActor, class FName Command, const struct FVector& Lever, bool SkipCommandPrerequisitiesCheck);
	void OnStop(class ULActBase* ReasonAction, class FName Reason);
	void OnStart();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AssultSlash_C">();
	}
	static class UBP_AssultSlash_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AssultSlash_C>();
	}
};
static_assert(alignof(UBP_AssultSlash_C) == 0x000008, "Wrong alignment on UBP_AssultSlash_C");
static_assert(sizeof(UBP_AssultSlash_C) == 0x000278, "Wrong size on UBP_AssultSlash_C");
static_assert(offsetof(UBP_AssultSlash_C, UberGraphFrame) == 0x000270, "Member 'UBP_AssultSlash_C::UberGraphFrame' has a wrong offset!");

}

