#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LightProp_Lamp_04

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_LightProp_Lamp_04.BP_LightProp_Lamp_04_C.NewFunction_0
// 0x0001 (0x0001 - 0x0000)
struct BP_LightProp_Lamp_04_C_NewFunction_0 final
{
public:
	bool                                          LightOn_0;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_LightProp_Lamp_04_C_NewFunction_0) == 0x000001, "Wrong alignment on BP_LightProp_Lamp_04_C_NewFunction_0");
static_assert(sizeof(BP_LightProp_Lamp_04_C_NewFunction_0) == 0x000001, "Wrong size on BP_LightProp_Lamp_04_C_NewFunction_0");
static_assert(offsetof(BP_LightProp_Lamp_04_C_NewFunction_0, LightOn_0) == 0x000000, "Member 'BP_LightProp_Lamp_04_C_NewFunction_0::LightOn_0' has a wrong offset!");

}

