#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LadderSpot

#include "Basic.hpp"

#include "ProjectP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LadderSpot.BP_LadderSpot_C
// 0x0000 (0x0378 - 0x0378)
class ABP_LadderSpot_C final : public ALPropLadderSpot
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LadderSpot_C">();
	}
	static class ABP_LadderSpot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LadderSpot_C>();
	}
};
static_assert(alignof(ABP_LadderSpot_C) == 0x000008, "Wrong alignment on ABP_LadderSpot_C");
static_assert(sizeof(ABP_LadderSpot_C) == 0x000378, "Wrong size on ABP_LadderSpot_C");

}

