#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Projectile_Design_SoldierFlameThrower

#include "Basic.hpp"

#include "BP_Projectile_Design_SoldierFlameThrower_classes.hpp"
#include "BP_Projectile_Design_SoldierFlameThrower_parameters.hpp"


namespace SDK
{

// Function BP_Projectile_Design_SoldierFlameThrower.BP_Projectile_Design_SoldierFlameThrower_C.CheckUseSubstituteSkillHit
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FLProjectileHitInfo              ProjectileHitInfo                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// struct FHitResult                       HitResult                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class FName                             ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class FName ABP_Projectile_Design_SoldierFlameThrower_C::CheckUseSubstituteSkillHit(const struct FLProjectileHitInfo& ProjectileHitInfo, const struct FHitResult& HitResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Projectile_Design_SoldierFlameThrower_C", "CheckUseSubstituteSkillHit");

	Params::BP_Projectile_Design_SoldierFlameThrower_C_CheckUseSubstituteSkillHit Parms{};

	Parms.ProjectileHitInfo = std::move(ProjectileHitInfo);
	Parms.HitResult = std::move(HitResult);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

