#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Stargazer

#include "Basic.hpp"

#include "ProjectPContentInfo_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_Stargazer.BP_Stargazer_C.Effect Ustable Change Etc NSHide
// 0x0050 (0x0050 - 0x0000)
struct BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide final
{
public:
	bool                                          Flag;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc_GetCurrentActiveMontage_ReturnValue;      // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_1;            // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc_GetCurrentActiveMontage_ReturnValue_1;    // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsVisible_ReturnValue_1;                  // 0x0042(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue;                     // 0x0043(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue_1;                   // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsVisible_ReturnValue_2;                  // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue_2;                   // 0x0046(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsVisible_ReturnValue_3;                  // 0x0047(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue_3;                   // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue_4;                   // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue_5;                   // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide) == 0x000008, "Wrong alignment on BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide");
static_assert(sizeof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide) == 0x000050, "Wrong size on BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, Flag) == 0x000000, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::Flag' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_GetAnimInstance_ReturnValue) == 0x000008, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsValid_ReturnValue) == 0x000010, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, K2Node_SwitchEnum_CmpSuccess) == 0x000011, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_GetCurrentActiveMontage_ReturnValue) == 0x000018, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_GetCurrentActiveMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsValid_ReturnValue_1) == 0x000020, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_GetAnimInstance_ReturnValue_1) == 0x000028, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_GetAnimInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, K2Node_SwitchEnum_CmpSuccess_1) == 0x000030, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::K2Node_SwitchEnum_CmpSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsValid_ReturnValue_2) == 0x000031, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_GetCurrentActiveMontage_ReturnValue_1) == 0x000038, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_GetCurrentActiveMontage_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsValid_ReturnValue_3) == 0x000040, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsVisible_ReturnValue) == 0x000041, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsVisible_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsVisible_ReturnValue_1) == 0x000042, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsVisible_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsActive_ReturnValue) == 0x000043, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsActive_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsActive_ReturnValue_1) == 0x000044, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsActive_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsVisible_ReturnValue_2) == 0x000045, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsVisible_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsActive_ReturnValue_2) == 0x000046, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsActive_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsVisible_ReturnValue_3) == 0x000047, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsVisible_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsActive_ReturnValue_3) == 0x000048, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsActive_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsActive_ReturnValue_4) == 0x000049, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsActive_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide, CallFunc_IsActive_ReturnValue_5) == 0x00004A, "Member 'BP_Stargazer_C_Effect_Ustable_Change_Etc_NSHide::CallFunc_IsActive_ReturnValue_5' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.GetInteractTime
// 0x0018 (0x0018 - 0x0000)
struct BP_Stargazer_C_GetInteractTime final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      K2Node_DynamicCast_AsAnim_Sequence_Base;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetPlayLength_ReturnValue;                // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_GetInteractTime) == 0x000008, "Wrong alignment on BP_Stargazer_C_GetInteractTime");
static_assert(sizeof(BP_Stargazer_C_GetInteractTime) == 0x000018, "Wrong size on BP_Stargazer_C_GetInteractTime");
static_assert(offsetof(BP_Stargazer_C_GetInteractTime, ReturnValue) == 0x000000, "Member 'BP_Stargazer_C_GetInteractTime::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_GetInteractTime, K2Node_DynamicCast_AsAnim_Sequence_Base) == 0x000008, "Member 'BP_Stargazer_C_GetInteractTime::K2Node_DynamicCast_AsAnim_Sequence_Base' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_GetInteractTime, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'BP_Stargazer_C_GetInteractTime::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_GetInteractTime, CallFunc_GetPlayLength_ReturnValue) == 0x000014, "Member 'BP_Stargazer_C_GetInteractTime::CallFunc_GetPlayLength_ReturnValue' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.SetCapsuleCollioion
// 0x0030 (0x0030 - 0x0000)
struct BP_Stargazer_C_SetCapsuleCollioion final
{
public:
	class UCapsuleComponent*                      Capsule;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Collision_on;                                      // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_CollisionProfile_LBlockingVolume_ReturnValue; // 0x000C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_GetObjectFName_ReturnValue;               // 0x0014(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_CollisionProfile_LBlockingVolume_ReturnValue_1; // 0x001C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchName_CmpSuccess;                      // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_CollisionProfile_NoCollision_ReturnValue; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_SetCapsuleCollioion) == 0x000008, "Wrong alignment on BP_Stargazer_C_SetCapsuleCollioion");
static_assert(sizeof(BP_Stargazer_C_SetCapsuleCollioion) == 0x000030, "Wrong size on BP_Stargazer_C_SetCapsuleCollioion");
static_assert(offsetof(BP_Stargazer_C_SetCapsuleCollioion, Capsule) == 0x000000, "Member 'BP_Stargazer_C_SetCapsuleCollioion::Capsule' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_SetCapsuleCollioion, Collision_on) == 0x000008, "Member 'BP_Stargazer_C_SetCapsuleCollioion::Collision_on' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_SetCapsuleCollioion, CallFunc_CollisionProfile_LBlockingVolume_ReturnValue) == 0x00000C, "Member 'BP_Stargazer_C_SetCapsuleCollioion::CallFunc_CollisionProfile_LBlockingVolume_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_SetCapsuleCollioion, CallFunc_GetObjectFName_ReturnValue) == 0x000014, "Member 'BP_Stargazer_C_SetCapsuleCollioion::CallFunc_GetObjectFName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_SetCapsuleCollioion, CallFunc_CollisionProfile_LBlockingVolume_ReturnValue_1) == 0x00001C, "Member 'BP_Stargazer_C_SetCapsuleCollioion::CallFunc_CollisionProfile_LBlockingVolume_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_SetCapsuleCollioion, K2Node_SwitchName_CmpSuccess) == 0x000024, "Member 'BP_Stargazer_C_SetCapsuleCollioion::K2Node_SwitchName_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_SetCapsuleCollioion, CallFunc_CollisionProfile_NoCollision_ReturnValue) == 0x000028, "Member 'BP_Stargazer_C_SetCapsuleCollioion::CallFunc_CollisionProfile_NoCollision_ReturnValue' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.EffectWaiting
// 0x0005 (0x0005 - 0x0000)
struct BP_Stargazer_C_EffectWaiting final
{
public:
	bool                                          Flag;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue;                     // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlaying_ReturnValue;                    // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlaying_ReturnValue_1;                  // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue_1;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Stargazer_C_EffectWaiting) == 0x000001, "Wrong alignment on BP_Stargazer_C_EffectWaiting");
static_assert(sizeof(BP_Stargazer_C_EffectWaiting) == 0x000005, "Wrong size on BP_Stargazer_C_EffectWaiting");
static_assert(offsetof(BP_Stargazer_C_EffectWaiting, Flag) == 0x000000, "Member 'BP_Stargazer_C_EffectWaiting::Flag' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_EffectWaiting, CallFunc_IsActive_ReturnValue) == 0x000001, "Member 'BP_Stargazer_C_EffectWaiting::CallFunc_IsActive_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_EffectWaiting, CallFunc_IsPlaying_ReturnValue) == 0x000002, "Member 'BP_Stargazer_C_EffectWaiting::CallFunc_IsPlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_EffectWaiting, CallFunc_IsPlaying_ReturnValue_1) == 0x000003, "Member 'BP_Stargazer_C_EffectWaiting::CallFunc_IsPlaying_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_EffectWaiting, CallFunc_IsActive_ReturnValue_1) == 0x000004, "Member 'BP_Stargazer_C_EffectWaiting::CallFunc_IsActive_ReturnValue_1' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.EffectActive
// 0x0007 (0x0007 - 0x0000)
struct BP_Stargazer_C_EffectActive final
{
public:
	bool                                          Flag;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue;                     // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue_1;                   // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlaying_ReturnValue;                    // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsPlaying_ReturnValue_1;                  // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue_2;                   // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue_3;                   // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Stargazer_C_EffectActive) == 0x000001, "Wrong alignment on BP_Stargazer_C_EffectActive");
static_assert(sizeof(BP_Stargazer_C_EffectActive) == 0x000007, "Wrong size on BP_Stargazer_C_EffectActive");
static_assert(offsetof(BP_Stargazer_C_EffectActive, Flag) == 0x000000, "Member 'BP_Stargazer_C_EffectActive::Flag' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_EffectActive, CallFunc_IsActive_ReturnValue) == 0x000001, "Member 'BP_Stargazer_C_EffectActive::CallFunc_IsActive_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_EffectActive, CallFunc_IsActive_ReturnValue_1) == 0x000002, "Member 'BP_Stargazer_C_EffectActive::CallFunc_IsActive_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_EffectActive, CallFunc_IsPlaying_ReturnValue) == 0x000003, "Member 'BP_Stargazer_C_EffectActive::CallFunc_IsPlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_EffectActive, CallFunc_IsPlaying_ReturnValue_1) == 0x000004, "Member 'BP_Stargazer_C_EffectActive::CallFunc_IsPlaying_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_EffectActive, CallFunc_IsActive_ReturnValue_2) == 0x000005, "Member 'BP_Stargazer_C_EffectActive::CallFunc_IsActive_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_EffectActive, CallFunc_IsActive_ReturnValue_3) == 0x000006, "Member 'BP_Stargazer_C_EffectActive::CallFunc_IsActive_ReturnValue_3' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnNotifyEnd_FDD8B0A44967396E14DF5EB814EA7840
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnNotifyEnd_FDD8B0A44967396E14DF5EB814EA7840 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnNotifyEnd_FDD8B0A44967396E14DF5EB814EA7840) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnNotifyEnd_FDD8B0A44967396E14DF5EB814EA7840");
static_assert(sizeof(BP_Stargazer_C_OnNotifyEnd_FDD8B0A44967396E14DF5EB814EA7840) == 0x000008, "Wrong size on BP_Stargazer_C_OnNotifyEnd_FDD8B0A44967396E14DF5EB814EA7840");
static_assert(offsetof(BP_Stargazer_C_OnNotifyEnd_FDD8B0A44967396E14DF5EB814EA7840, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnNotifyEnd_FDD8B0A44967396E14DF5EB814EA7840::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnNotifyBegin_FDD8B0A44967396E14DF5EB814EA7840
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnNotifyBegin_FDD8B0A44967396E14DF5EB814EA7840 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnNotifyBegin_FDD8B0A44967396E14DF5EB814EA7840) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnNotifyBegin_FDD8B0A44967396E14DF5EB814EA7840");
static_assert(sizeof(BP_Stargazer_C_OnNotifyBegin_FDD8B0A44967396E14DF5EB814EA7840) == 0x000008, "Wrong size on BP_Stargazer_C_OnNotifyBegin_FDD8B0A44967396E14DF5EB814EA7840");
static_assert(offsetof(BP_Stargazer_C_OnNotifyBegin_FDD8B0A44967396E14DF5EB814EA7840, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnNotifyBegin_FDD8B0A44967396E14DF5EB814EA7840::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnInterrupted_FDD8B0A44967396E14DF5EB814EA7840
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnInterrupted_FDD8B0A44967396E14DF5EB814EA7840 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnInterrupted_FDD8B0A44967396E14DF5EB814EA7840) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnInterrupted_FDD8B0A44967396E14DF5EB814EA7840");
static_assert(sizeof(BP_Stargazer_C_OnInterrupted_FDD8B0A44967396E14DF5EB814EA7840) == 0x000008, "Wrong size on BP_Stargazer_C_OnInterrupted_FDD8B0A44967396E14DF5EB814EA7840");
static_assert(offsetof(BP_Stargazer_C_OnInterrupted_FDD8B0A44967396E14DF5EB814EA7840, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnInterrupted_FDD8B0A44967396E14DF5EB814EA7840::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnBlendOut_FDD8B0A44967396E14DF5EB814EA7840
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnBlendOut_FDD8B0A44967396E14DF5EB814EA7840 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnBlendOut_FDD8B0A44967396E14DF5EB814EA7840) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnBlendOut_FDD8B0A44967396E14DF5EB814EA7840");
static_assert(sizeof(BP_Stargazer_C_OnBlendOut_FDD8B0A44967396E14DF5EB814EA7840) == 0x000008, "Wrong size on BP_Stargazer_C_OnBlendOut_FDD8B0A44967396E14DF5EB814EA7840");
static_assert(offsetof(BP_Stargazer_C_OnBlendOut_FDD8B0A44967396E14DF5EB814EA7840, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnBlendOut_FDD8B0A44967396E14DF5EB814EA7840::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnCompleted_FDD8B0A44967396E14DF5EB814EA7840
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnCompleted_FDD8B0A44967396E14DF5EB814EA7840 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnCompleted_FDD8B0A44967396E14DF5EB814EA7840) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnCompleted_FDD8B0A44967396E14DF5EB814EA7840");
static_assert(sizeof(BP_Stargazer_C_OnCompleted_FDD8B0A44967396E14DF5EB814EA7840) == 0x000008, "Wrong size on BP_Stargazer_C_OnCompleted_FDD8B0A44967396E14DF5EB814EA7840");
static_assert(offsetof(BP_Stargazer_C_OnCompleted_FDD8B0A44967396E14DF5EB814EA7840, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnCompleted_FDD8B0A44967396E14DF5EB814EA7840::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnNotifyEnd_0827B6FB4BDE6917D21174812235DDF9
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnNotifyEnd_0827B6FB4BDE6917D21174812235DDF9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnNotifyEnd_0827B6FB4BDE6917D21174812235DDF9) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnNotifyEnd_0827B6FB4BDE6917D21174812235DDF9");
static_assert(sizeof(BP_Stargazer_C_OnNotifyEnd_0827B6FB4BDE6917D21174812235DDF9) == 0x000008, "Wrong size on BP_Stargazer_C_OnNotifyEnd_0827B6FB4BDE6917D21174812235DDF9");
static_assert(offsetof(BP_Stargazer_C_OnNotifyEnd_0827B6FB4BDE6917D21174812235DDF9, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnNotifyEnd_0827B6FB4BDE6917D21174812235DDF9::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnNotifyBegin_0827B6FB4BDE6917D21174812235DDF9
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnNotifyBegin_0827B6FB4BDE6917D21174812235DDF9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnNotifyBegin_0827B6FB4BDE6917D21174812235DDF9) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnNotifyBegin_0827B6FB4BDE6917D21174812235DDF9");
static_assert(sizeof(BP_Stargazer_C_OnNotifyBegin_0827B6FB4BDE6917D21174812235DDF9) == 0x000008, "Wrong size on BP_Stargazer_C_OnNotifyBegin_0827B6FB4BDE6917D21174812235DDF9");
static_assert(offsetof(BP_Stargazer_C_OnNotifyBegin_0827B6FB4BDE6917D21174812235DDF9, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnNotifyBegin_0827B6FB4BDE6917D21174812235DDF9::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnInterrupted_0827B6FB4BDE6917D21174812235DDF9
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnInterrupted_0827B6FB4BDE6917D21174812235DDF9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnInterrupted_0827B6FB4BDE6917D21174812235DDF9) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnInterrupted_0827B6FB4BDE6917D21174812235DDF9");
static_assert(sizeof(BP_Stargazer_C_OnInterrupted_0827B6FB4BDE6917D21174812235DDF9) == 0x000008, "Wrong size on BP_Stargazer_C_OnInterrupted_0827B6FB4BDE6917D21174812235DDF9");
static_assert(offsetof(BP_Stargazer_C_OnInterrupted_0827B6FB4BDE6917D21174812235DDF9, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnInterrupted_0827B6FB4BDE6917D21174812235DDF9::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnBlendOut_0827B6FB4BDE6917D21174812235DDF9
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnBlendOut_0827B6FB4BDE6917D21174812235DDF9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnBlendOut_0827B6FB4BDE6917D21174812235DDF9) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnBlendOut_0827B6FB4BDE6917D21174812235DDF9");
static_assert(sizeof(BP_Stargazer_C_OnBlendOut_0827B6FB4BDE6917D21174812235DDF9) == 0x000008, "Wrong size on BP_Stargazer_C_OnBlendOut_0827B6FB4BDE6917D21174812235DDF9");
static_assert(offsetof(BP_Stargazer_C_OnBlendOut_0827B6FB4BDE6917D21174812235DDF9, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnBlendOut_0827B6FB4BDE6917D21174812235DDF9::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnCompleted_0827B6FB4BDE6917D21174812235DDF9
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnCompleted_0827B6FB4BDE6917D21174812235DDF9 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnCompleted_0827B6FB4BDE6917D21174812235DDF9) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnCompleted_0827B6FB4BDE6917D21174812235DDF9");
static_assert(sizeof(BP_Stargazer_C_OnCompleted_0827B6FB4BDE6917D21174812235DDF9) == 0x000008, "Wrong size on BP_Stargazer_C_OnCompleted_0827B6FB4BDE6917D21174812235DDF9");
static_assert(offsetof(BP_Stargazer_C_OnCompleted_0827B6FB4BDE6917D21174812235DDF9, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnCompleted_0827B6FB4BDE6917D21174812235DDF9::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnNotifyEnd_FE326EFE4736A40794D5429C2AA03C25
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnNotifyEnd_FE326EFE4736A40794D5429C2AA03C25 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnNotifyEnd_FE326EFE4736A40794D5429C2AA03C25) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnNotifyEnd_FE326EFE4736A40794D5429C2AA03C25");
static_assert(sizeof(BP_Stargazer_C_OnNotifyEnd_FE326EFE4736A40794D5429C2AA03C25) == 0x000008, "Wrong size on BP_Stargazer_C_OnNotifyEnd_FE326EFE4736A40794D5429C2AA03C25");
static_assert(offsetof(BP_Stargazer_C_OnNotifyEnd_FE326EFE4736A40794D5429C2AA03C25, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnNotifyEnd_FE326EFE4736A40794D5429C2AA03C25::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnNotifyBegin_FE326EFE4736A40794D5429C2AA03C25
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnNotifyBegin_FE326EFE4736A40794D5429C2AA03C25 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnNotifyBegin_FE326EFE4736A40794D5429C2AA03C25) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnNotifyBegin_FE326EFE4736A40794D5429C2AA03C25");
static_assert(sizeof(BP_Stargazer_C_OnNotifyBegin_FE326EFE4736A40794D5429C2AA03C25) == 0x000008, "Wrong size on BP_Stargazer_C_OnNotifyBegin_FE326EFE4736A40794D5429C2AA03C25");
static_assert(offsetof(BP_Stargazer_C_OnNotifyBegin_FE326EFE4736A40794D5429C2AA03C25, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnNotifyBegin_FE326EFE4736A40794D5429C2AA03C25::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnInterrupted_FE326EFE4736A40794D5429C2AA03C25
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnInterrupted_FE326EFE4736A40794D5429C2AA03C25 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnInterrupted_FE326EFE4736A40794D5429C2AA03C25) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnInterrupted_FE326EFE4736A40794D5429C2AA03C25");
static_assert(sizeof(BP_Stargazer_C_OnInterrupted_FE326EFE4736A40794D5429C2AA03C25) == 0x000008, "Wrong size on BP_Stargazer_C_OnInterrupted_FE326EFE4736A40794D5429C2AA03C25");
static_assert(offsetof(BP_Stargazer_C_OnInterrupted_FE326EFE4736A40794D5429C2AA03C25, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnInterrupted_FE326EFE4736A40794D5429C2AA03C25::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnBlendOut_FE326EFE4736A40794D5429C2AA03C25
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnBlendOut_FE326EFE4736A40794D5429C2AA03C25 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnBlendOut_FE326EFE4736A40794D5429C2AA03C25) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnBlendOut_FE326EFE4736A40794D5429C2AA03C25");
static_assert(sizeof(BP_Stargazer_C_OnBlendOut_FE326EFE4736A40794D5429C2AA03C25) == 0x000008, "Wrong size on BP_Stargazer_C_OnBlendOut_FE326EFE4736A40794D5429C2AA03C25");
static_assert(offsetof(BP_Stargazer_C_OnBlendOut_FE326EFE4736A40794D5429C2AA03C25, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnBlendOut_FE326EFE4736A40794D5429C2AA03C25::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnCompleted_FE326EFE4736A40794D5429C2AA03C25
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnCompleted_FE326EFE4736A40794D5429C2AA03C25 final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnCompleted_FE326EFE4736A40794D5429C2AA03C25) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnCompleted_FE326EFE4736A40794D5429C2AA03C25");
static_assert(sizeof(BP_Stargazer_C_OnCompleted_FE326EFE4736A40794D5429C2AA03C25) == 0x000008, "Wrong size on BP_Stargazer_C_OnCompleted_FE326EFE4736A40794D5429C2AA03C25");
static_assert(offsetof(BP_Stargazer_C_OnCompleted_FE326EFE4736A40794D5429C2AA03C25, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnCompleted_FE326EFE4736A40794D5429C2AA03C25::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnNotifyEnd_0DF816A84C90EF26D61C4AB78C76201D
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnNotifyEnd_0DF816A84C90EF26D61C4AB78C76201D final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnNotifyEnd_0DF816A84C90EF26D61C4AB78C76201D) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnNotifyEnd_0DF816A84C90EF26D61C4AB78C76201D");
static_assert(sizeof(BP_Stargazer_C_OnNotifyEnd_0DF816A84C90EF26D61C4AB78C76201D) == 0x000008, "Wrong size on BP_Stargazer_C_OnNotifyEnd_0DF816A84C90EF26D61C4AB78C76201D");
static_assert(offsetof(BP_Stargazer_C_OnNotifyEnd_0DF816A84C90EF26D61C4AB78C76201D, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnNotifyEnd_0DF816A84C90EF26D61C4AB78C76201D::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnNotifyBegin_0DF816A84C90EF26D61C4AB78C76201D
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnNotifyBegin_0DF816A84C90EF26D61C4AB78C76201D final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnNotifyBegin_0DF816A84C90EF26D61C4AB78C76201D) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnNotifyBegin_0DF816A84C90EF26D61C4AB78C76201D");
static_assert(sizeof(BP_Stargazer_C_OnNotifyBegin_0DF816A84C90EF26D61C4AB78C76201D) == 0x000008, "Wrong size on BP_Stargazer_C_OnNotifyBegin_0DF816A84C90EF26D61C4AB78C76201D");
static_assert(offsetof(BP_Stargazer_C_OnNotifyBegin_0DF816A84C90EF26D61C4AB78C76201D, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnNotifyBegin_0DF816A84C90EF26D61C4AB78C76201D::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnInterrupted_0DF816A84C90EF26D61C4AB78C76201D
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnInterrupted_0DF816A84C90EF26D61C4AB78C76201D final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnInterrupted_0DF816A84C90EF26D61C4AB78C76201D) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnInterrupted_0DF816A84C90EF26D61C4AB78C76201D");
static_assert(sizeof(BP_Stargazer_C_OnInterrupted_0DF816A84C90EF26D61C4AB78C76201D) == 0x000008, "Wrong size on BP_Stargazer_C_OnInterrupted_0DF816A84C90EF26D61C4AB78C76201D");
static_assert(offsetof(BP_Stargazer_C_OnInterrupted_0DF816A84C90EF26D61C4AB78C76201D, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnInterrupted_0DF816A84C90EF26D61C4AB78C76201D::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnBlendOut_0DF816A84C90EF26D61C4AB78C76201D
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnBlendOut_0DF816A84C90EF26D61C4AB78C76201D final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnBlendOut_0DF816A84C90EF26D61C4AB78C76201D) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnBlendOut_0DF816A84C90EF26D61C4AB78C76201D");
static_assert(sizeof(BP_Stargazer_C_OnBlendOut_0DF816A84C90EF26D61C4AB78C76201D) == 0x000008, "Wrong size on BP_Stargazer_C_OnBlendOut_0DF816A84C90EF26D61C4AB78C76201D");
static_assert(offsetof(BP_Stargazer_C_OnBlendOut_0DF816A84C90EF26D61C4AB78C76201D, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnBlendOut_0DF816A84C90EF26D61C4AB78C76201D::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.OnCompleted_0DF816A84C90EF26D61C4AB78C76201D
// 0x0008 (0x0008 - 0x0000)
struct BP_Stargazer_C_OnCompleted_0DF816A84C90EF26D61C4AB78C76201D final
{
public:
	class FName                                   NotifyName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_OnCompleted_0DF816A84C90EF26D61C4AB78C76201D) == 0x000004, "Wrong alignment on BP_Stargazer_C_OnCompleted_0DF816A84C90EF26D61C4AB78C76201D");
static_assert(sizeof(BP_Stargazer_C_OnCompleted_0DF816A84C90EF26D61C4AB78C76201D) == 0x000008, "Wrong size on BP_Stargazer_C_OnCompleted_0DF816A84C90EF26D61C4AB78C76201D");
static_assert(offsetof(BP_Stargazer_C_OnCompleted_0DF816A84C90EF26D61C4AB78C76201D, NotifyName) == 0x000000, "Member 'BP_Stargazer_C_OnCompleted_0DF816A84C90EF26D61C4AB78C76201D::NotifyName' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_Stargazer_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_Stargazer_C_ReceiveTick");
static_assert(sizeof(BP_Stargazer_C_ReceiveTick) == 0x000004, "Wrong size on BP_Stargazer_C_ReceiveTick");
static_assert(offsetof(BP_Stargazer_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_Stargazer_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.SetStargazerType
// 0x0001 (0x0001 - 0x0000)
struct BP_Stargazer_C_SetStargazerType final
{
public:
	ELStargazerType                               StateData;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_Stargazer_C_SetStargazerType) == 0x000001, "Wrong alignment on BP_Stargazer_C_SetStargazerType");
static_assert(sizeof(BP_Stargazer_C_SetStargazerType) == 0x000001, "Wrong size on BP_Stargazer_C_SetStargazerType");
static_assert(offsetof(BP_Stargazer_C_SetStargazerType, StateData) == 0x000000, "Member 'BP_Stargazer_C_SetStargazerType::StateData' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.SetStargazerUnstable
// 0x0001 (0x0001 - 0x0000)
struct BP_Stargazer_C_SetStargazerUnstable final
{
public:
	bool                                          Unstable;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Stargazer_C_SetStargazerUnstable) == 0x000001, "Wrong alignment on BP_Stargazer_C_SetStargazerUnstable");
static_assert(sizeof(BP_Stargazer_C_SetStargazerUnstable) == 0x000001, "Wrong size on BP_Stargazer_C_SetStargazerUnstable");
static_assert(offsetof(BP_Stargazer_C_SetStargazerUnstable, Unstable) == 0x000000, "Member 'BP_Stargazer_C_SetStargazerUnstable::Unstable' has a wrong offset!");

// Function BP_Stargazer.BP_Stargazer_C.ExecuteUbergraph_BP_Stargazer
// 0x02E0 (0x02E0 - 0x0000)
struct BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Temp_name_Variable;                                // 0x0004(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_CustomEvent_NotifyName_14;                  // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate;              // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_13;                  // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_1;            // 0x0030(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_12;                  // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_2;            // 0x0048(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_11;                  // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_3;            // 0x0060(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_10;                  // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_4;            // 0x0078(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   Temp_name_Variable_1;                              // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_5;            // 0x0090(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_9;                   // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_8;                   // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_6;            // 0x00B0(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_7;                   // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_7;            // 0x00C8(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_6;                   // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_8;            // 0x00E0(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_5;                   // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_9;            // 0x00F8(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   Temp_name_Variable_2;                              // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_10;           // 0x0110(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_4;                   // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_CustomEvent_NotifyName_3;                   // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_11;           // 0x0130(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_2;                   // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_12;           // 0x0148(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_1;                   // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_13;           // 0x0160(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName;                     // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_14;           // 0x0178(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   Temp_name_Variable_3;                              // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_15;           // 0x0190(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_17;                  // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_16;           // 0x01A8(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_18;                  // 0x01B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x01C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ELStargazerType                               K2Node_Event_StateData;                            // 0x01C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C5[0x3];                                      // 0x01C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D1[0x7];                                      // 0x01D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc_GetCurrentActiveMontage_ReturnValue;      // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue; // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x01EA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x01EB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x01EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1ED[0x3];                                      // 0x01ED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_1;            // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1F9[0x7];                                      // 0x01F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc_GetCurrentActiveMontage_ReturnValue_1;    // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1; // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0210(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0211(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_212[0x2];                                      // 0x0212(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_CustomEvent_NotifyName_15;                  // 0x0214(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_17;           // 0x021C(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   K2Node_CustomEvent_NotifyName_19;                  // 0x022C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x0234(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_235[0x3];                                      // 0x0235(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_2;            // 0x0238(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x0240(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_241[0x7];                                      // 0x0241(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc_GetCurrentActiveMontage_ReturnValue_2;    // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2; // 0x0250(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x0258(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_11;                   // 0x0259(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_12;                   // 0x025A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25B[0x5];                                      // 0x025B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue_3;            // 0x0260(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_13;                   // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_269[0x7];                                      // 0x0269(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimMontage*                           CallFunc_GetCurrentActiveMontage_ReturnValue_3;    // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayMontageCallbackProxy*              CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3; // 0x0278(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_14;                   // 0x0280(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_15;                   // 0x0281(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_282[0x2];                                      // 0x0282(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Montage_GetCurrentSection_ReturnValue;    // 0x0284(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x028C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_28D[0x3];                                      // 0x028D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_18;           // 0x0290(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_19;           // 0x02A0(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsActive_ReturnValue;                     // 0x02B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2B1[0x3];                                      // 0x02B1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_CustomEvent_NotifyName_16;                  // 0x02B4(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x02BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_Unstable;                             // 0x02BD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess_2;                    // 0x02BE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_BoolBool_ReturnValue;            // 0x02BF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TDelegate<void(class FName NotifyName)>       K2Node_CreateDelegate_OutputDelegate_20;           // 0x02C0(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x02D0(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsActive_ReturnValue_1;                   // 0x02D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer) == 0x000008, "Wrong alignment on BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer");
static_assert(sizeof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer) == 0x0002E0, "Wrong size on BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, EntryPoint) == 0x000000, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, Temp_name_Variable) == 0x000004, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_SwitchEnum_CmpSuccess) == 0x00000C, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_14) == 0x000010, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_14' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate) == 0x000018, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_13) == 0x000028, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_13' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_1) == 0x000030, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_12) == 0x000040, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_12' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_2) == 0x000048, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_11) == 0x000058, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_11' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_3) == 0x000060, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_10) == 0x000070, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_10' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_4) == 0x000078, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, Temp_name_Variable_1) == 0x000088, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::Temp_name_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_5) == 0x000090, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_9) == 0x0000A0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_9' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_8) == 0x0000A8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_8' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_6) == 0x0000B0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_7) == 0x0000C0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_7' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_7) == 0x0000C8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_7' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_6) == 0x0000D8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_6' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_8) == 0x0000E0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_8' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_5) == 0x0000F0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_5' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_9) == 0x0000F8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_9' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, Temp_name_Variable_2) == 0x000108, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::Temp_name_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_10) == 0x000110, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_10' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_4) == 0x000120, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_4' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_3) == 0x000128, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_3' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_11) == 0x000130, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_11' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_2) == 0x000140, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_12) == 0x000148, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_12' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_1) == 0x000158, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_13) == 0x000160, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_13' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName) == 0x000170, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_14) == 0x000178, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_14' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, Temp_name_Variable_3) == 0x000188, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::Temp_name_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_15) == 0x000190, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_15' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_17) == 0x0001A0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_17' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_16) == 0x0001A8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_16' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_18) == 0x0001B8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_18' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_Event_DeltaSeconds) == 0x0001C0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_Event_StateData) == 0x0001C4, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_Event_StateData' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_GetAnimInstance_ReturnValue) == 0x0001C8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue) == 0x0001D0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_GetCurrentActiveMontage_ReturnValue) == 0x0001D8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_GetCurrentActiveMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue) == 0x0001E0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_1) == 0x0001E8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_2) == 0x0001E9, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_SwitchEnum_CmpSuccess_1) == 0x0001EA, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_SwitchEnum_CmpSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_3) == 0x0001EB, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_4) == 0x0001EC, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_GetAnimInstance_ReturnValue_1) == 0x0001F0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_GetAnimInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_5) == 0x0001F8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_GetCurrentActiveMontage_ReturnValue_1) == 0x000200, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_GetCurrentActiveMontage_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1) == 0x000208, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_6) == 0x000210, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_7) == 0x000211, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_15) == 0x000214, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_15' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_17) == 0x00021C, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_17' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_19) == 0x00022C, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_19' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_8) == 0x000234, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_GetAnimInstance_ReturnValue_2) == 0x000238, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_GetAnimInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_9) == 0x000240, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_GetCurrentActiveMontage_ReturnValue_2) == 0x000248, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_GetCurrentActiveMontage_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2) == 0x000250, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_10) == 0x000258, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_11) == 0x000259, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_12) == 0x00025A, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_GetAnimInstance_ReturnValue_3) == 0x000260, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_GetAnimInstance_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_13) == 0x000268, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_13' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_GetCurrentActiveMontage_ReturnValue_3) == 0x000270, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_GetCurrentActiveMontage_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3) == 0x000278, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_CreateProxyObjectForPlayMontage_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_14) == 0x000280, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_14' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsValid_ReturnValue_15) == 0x000281, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsValid_ReturnValue_15' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_Montage_GetCurrentSection_ReturnValue) == 0x000284, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_Montage_GetCurrentSection_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_EqualEqual_NameName_ReturnValue) == 0x00028C, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_EqualEqual_NameName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_18) == 0x000290, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_18' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_19) == 0x0002A0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_19' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsActive_ReturnValue) == 0x0002B0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsActive_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CustomEvent_NotifyName_16) == 0x0002B4, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CustomEvent_NotifyName_16' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x0002BC, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_Event_Unstable) == 0x0002BD, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_Event_Unstable' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_SwitchEnum_CmpSuccess_2) == 0x0002BE, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_SwitchEnum_CmpSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_NotEqual_BoolBool_ReturnValue) == 0x0002BF, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_NotEqual_BoolBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, K2Node_CreateDelegate_OutputDelegate_20) == 0x0002C0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::K2Node_CreateDelegate_OutputDelegate_20' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x0002D0, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer, CallFunc_IsActive_ReturnValue_1) == 0x0002D8, "Member 'BP_Stargazer_C_ExecuteUbergraph_BP_Stargazer::CallFunc_IsActive_ReturnValue_1' has a wrong offset!");

}

