#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CWBP_Template_AlignCurve

#include "Basic.hpp"

#include "CWBP_Template_AlignCurve_classes.hpp"
#include "CWBP_Template_AlignCurve_parameters.hpp"


namespace SDK
{

// Function CWBP_Template_AlignCurve.CWBP_Template_AlignCurve_C.ExecuteUbergraph_CWBP_Template_AlignCurve
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACWBP_Template_AlignCurve_C::ExecuteUbergraph_CWBP_Template_AlignCurve(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CWBP_Template_AlignCurve_C", "ExecuteUbergraph_CWBP_Template_AlignCurve");

	Params::CWBP_Template_AlignCurve_C_ExecuteUbergraph_CWBP_Template_AlignCurve Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CWBP_Template_AlignCurve.CWBP_Template_AlignCurve_C.CurveUpdateLocation
// (BlueprintCallable, BlueprintEvent)

void ACWBP_Template_AlignCurve_C::CurveUpdateLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CWBP_Template_AlignCurve_C", "CurveUpdateLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CWBP_Template_AlignCurve.CWBP_Template_AlignCurve_C.CurveUpdateRotation
// (BlueprintCallable, BlueprintEvent)

void ACWBP_Template_AlignCurve_C::CurveUpdateRotation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CWBP_Template_AlignCurve_C", "CurveUpdateRotation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CWBP_Template_AlignCurve.CWBP_Template_AlignCurve_C.OnStopWork
// (Event, Public, BlueprintEvent)

void ACWBP_Template_AlignCurve_C::OnStopWork()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CWBP_Template_AlignCurve_C", "OnStopWork");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CWBP_Template_AlignCurve.CWBP_Template_AlignCurve_C.CurveStopTimeLine
// (BlueprintCallable, BlueprintEvent)

void ACWBP_Template_AlignCurve_C::CurveStopTimeLine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CWBP_Template_AlignCurve_C", "CurveStopTimeLine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CWBP_Template_AlignCurve.CWBP_Template_AlignCurve_C.CurvePlayTimeLine
// (BlueprintCallable, BlueprintEvent)

void ACWBP_Template_AlignCurve_C::CurvePlayTimeLine()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CWBP_Template_AlignCurve_C", "CurvePlayTimeLine");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CWBP_Template_AlignCurve.CWBP_Template_AlignCurve_C.OnChangeBlend
// (Event, Public, BlueprintEvent)
// Parameters:
// ELCameraWorkBlendState                  CameraWorkBlendState                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACWBP_Template_AlignCurve_C::OnChangeBlend(ELCameraWorkBlendState CameraWorkBlendState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CWBP_Template_AlignCurve_C", "OnChangeBlend");

	Params::CWBP_Template_AlignCurve_C_OnChangeBlend Parms{};

	Parms.CameraWorkBlendState = CameraWorkBlendState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CWBP_Template_AlignCurve.CWBP_Template_AlignCurve_C.OnStartWork
// (Event, Public, BlueprintEvent)

void ACWBP_Template_AlignCurve_C::OnStartWork()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CWBP_Template_AlignCurve_C", "OnStartWork");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CWBP_Template_AlignCurve.CWBP_Template_AlignCurve_C.UpdateTargetView
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ACWBP_Template_AlignCurve_C::UpdateTargetView(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CWBP_Template_AlignCurve_C", "UpdateTargetView");

	Params::CWBP_Template_AlignCurve_C_UpdateTargetView Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

