#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LV_Krat_Factory_Sound

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LV_Krat_Factory_Sound.LV_Krat_Factory_Sound_C
// 0x0010 (0x01F8 - 0x01E8)
class ALV_Krat_Factory_Sound_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AAmbientSound*                          AMB_MS_Secret_Room_ExecuteUbergraph_LV_Krat_Factory_Sound_RefProperty; // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_LV_Krat_Factory_Sound(int32 EntryPoint);
	void BndEvt__LV_Krat_Factory_Sound_AMB_TR_Factory_Inside_02_K2Node_ActorBoundEvent_4_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
	void BndEvt__LV_Krat_Factory_Sound_AMB_TR_Factory_Inside_02_K2Node_ActorBoundEvent_3_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
	void BndEvt__LV_Krat_Factory_Sound_AMB_TR_Factory_Inside_K2Node_ActorBoundEvent_2_ActorEndOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
	void BndEvt__LV_Krat_Factory_Sound_AMB_TR_Factory_Inside_K2Node_ActorBoundEvent_1_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);
	void BndEvt__LV_Krat_Factory_Sound_AMB_TR_Secret_Room_IO_K2Node_ActorBoundEvent_0_ActorBeginOverlapSignature__DelegateSignature(class AActor* OverlappedActor, class AActor* OtherActor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LV_Krat_Factory_Sound_C">();
	}
	static class ALV_Krat_Factory_Sound_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALV_Krat_Factory_Sound_C>();
	}
};
static_assert(alignof(ALV_Krat_Factory_Sound_C) == 0x000008, "Wrong alignment on ALV_Krat_Factory_Sound_C");
static_assert(sizeof(ALV_Krat_Factory_Sound_C) == 0x0001F8, "Wrong size on ALV_Krat_Factory_Sound_C");
static_assert(offsetof(ALV_Krat_Factory_Sound_C, UberGraphFrame) == 0x0001E8, "Member 'ALV_Krat_Factory_Sound_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ALV_Krat_Factory_Sound_C, AMB_MS_Secret_Room_ExecuteUbergraph_LV_Krat_Factory_Sound_RefProperty) == 0x0001F0, "Member 'ALV_Krat_Factory_Sound_C::AMB_MS_Secret_Room_ExecuteUbergraph_LV_Krat_Factory_Sound_RefProperty' has a wrong offset!");

}

