#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIBP_ListData_Controller

#include "Basic.hpp"

#include "UIBP_ListData_Controller_classes.hpp"
#include "UIBP_ListData_Controller_parameters.hpp"


namespace SDK
{

// Function UIBP_ListData_Controller.UIBP_ListData_Controller_C.OnChanging__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsChanging                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIBP_ListData_Controller_C::OnChanging__DelegateSignature(bool IsChanging)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIBP_ListData_Controller_C", "OnChanging__DelegateSignature");

	Params::UIBP_ListData_Controller_C_OnChanging__DelegateSignature Parms{};

	Parms.IsChanging = IsChanging;

	UObject::ProcessEvent(Func, &Parms);
}

}

