#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIBP_ListData_WeaponPart

#include "Basic.hpp"

#include "UIEN_WeaponPart_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UIBP_ListData_WeaponPart.UIBP_ListData_WeaponPart_C
// 0x0008 (0x0030 - 0x0028)
class UUIBP_ListData_WeaponPart_C final : public UObject
{
public:
	EUIEN_WeaponPart                              WeaponPart;                                        // 0x0028(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          Enabled;                                           // 0x0029(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UIBP_ListData_WeaponPart_C">();
	}
	static class UUIBP_ListData_WeaponPart_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIBP_ListData_WeaponPart_C>();
	}
};
static_assert(alignof(UUIBP_ListData_WeaponPart_C) == 0x000008, "Wrong alignment on UUIBP_ListData_WeaponPart_C");
static_assert(sizeof(UUIBP_ListData_WeaponPart_C) == 0x000030, "Wrong size on UUIBP_ListData_WeaponPart_C");
static_assert(offsetof(UUIBP_ListData_WeaponPart_C, WeaponPart) == 0x000028, "Member 'UUIBP_ListData_WeaponPart_C::WeaponPart' has a wrong offset!");
static_assert(offsetof(UUIBP_ListData_WeaponPart_C, Enabled) == 0x000029, "Member 'UUIBP_ListData_WeaponPart_C::Enabled' has a wrong offset!");

}

