#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_HUD_GaugeFX

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UIW_HUD_GaugeFX.UIW_HUD_GaugeFX_C
// 0x0010 (0x0278 - 0x0268)
class UUIW_HUD_GaugeFX_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0268(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Ani_Visible;                                       // 0x0270(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UIW_HUD_GaugeFX(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UIW_HUD_GaugeFX_C">();
	}
	static class UUIW_HUD_GaugeFX_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUIW_HUD_GaugeFX_C>();
	}
};
static_assert(alignof(UUIW_HUD_GaugeFX_C) == 0x000008, "Wrong alignment on UUIW_HUD_GaugeFX_C");
static_assert(sizeof(UUIW_HUD_GaugeFX_C) == 0x000278, "Wrong size on UUIW_HUD_GaugeFX_C");
static_assert(offsetof(UUIW_HUD_GaugeFX_C, UberGraphFrame) == 0x000268, "Member 'UUIW_HUD_GaugeFX_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUIW_HUD_GaugeFX_C, Ani_Visible) == 0x000270, "Member 'UUIW_HUD_GaugeFX_C::Ani_Visible' has a wrong offset!");

}

