#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UIW_NPCDialog_GoldenTree

#include "Basic.hpp"

#include "UIW_NPCDialog_GoldenTree_classes.hpp"
#include "UIW_NPCDialog_GoldenTree_parameters.hpp"


namespace SDK
{

// Function UIW_NPCDialog_GoldenTree.UIW_NPCDialog_GoldenTree_C.ExecuteUbergraph_UIW_NPCDialog_GoldenTree
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_NPCDialog_GoldenTree_C::ExecuteUbergraph_UIW_NPCDialog_GoldenTree(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_NPCDialog_GoldenTree_C", "ExecuteUbergraph_UIW_NPCDialog_GoldenTree");

	Params::UIW_NPCDialog_GoldenTree_C_ExecuteUbergraph_UIW_NPCDialog_GoldenTree Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_NPCDialog_GoldenTree.UIW_NPCDialog_GoldenTree_C.SetView_Full
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsFull                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_NPCDialog_GoldenTree_C::SetView_Full(bool IsFull)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_NPCDialog_GoldenTree_C", "SetView_Full");

	Params::UIW_NPCDialog_GoldenTree_C_SetView_Full Parms{};

	Parms.IsFull = IsFull;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_NPCDialog_GoldenTree.UIW_NPCDialog_GoldenTree_C.SetView_Boost
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsBoost                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float                                   Percent                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             TimeText                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UUIW_NPCDialog_GoldenTree_C::SetView_Boost(bool IsBoost, float Percent, const class FText& TimeText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_NPCDialog_GoldenTree_C", "SetView_Boost");

	Params::UIW_NPCDialog_GoldenTree_C_SetView_Boost Parms{};

	Parms.IsBoost = IsBoost;
	Parms.Percent = Percent;
	Parms.TimeText = std::move(TimeText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_NPCDialog_GoldenTree.UIW_NPCDialog_GoldenTree_C.SetView_Show
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsShow                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUIW_NPCDialog_GoldenTree_C::SetView_Show(bool IsShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_NPCDialog_GoldenTree_C", "SetView_Show");

	Params::UIW_NPCDialog_GoldenTree_C_SetView_Show Parms{};

	Parms.IsShow = IsShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_NPCDialog_GoldenTree.UIW_NPCDialog_GoldenTree_C.OnReady
// (BlueprintCallable, BlueprintEvent)

void UUIW_NPCDialog_GoldenTree_C::OnReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_NPCDialog_GoldenTree_C", "OnReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UIW_NPCDialog_GoldenTree.UIW_NPCDialog_GoldenTree_C.SetView_CoinCount
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsFull                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FText                             CountText                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             TimeText                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUIW_NPCDialog_GoldenTree_C::SetView_CoinCount(bool IsFull, const class FText& CountText, const class FText& TimeText, int32 Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_NPCDialog_GoldenTree_C", "SetView_CoinCount");

	Params::UIW_NPCDialog_GoldenTree_C_SetView_CoinCount Parms{};

	Parms.IsFull = IsFull;
	Parms.CountText = std::move(CountText);
	Parms.TimeText = std::move(TimeText);
	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UIW_NPCDialog_GoldenTree.UIW_NPCDialog_GoldenTree_C.OnInitialized
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUIW_NPCDialog_GoldenTree_C::OnInitialized()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UIW_NPCDialog_GoldenTree_C", "OnInitialized");

	UObject::ProcessEvent(Func, nullptr);
}

}

