name: MSBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./Liesofp_dlc.sln
  tag1: V${{ github.run_number }}

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release, Debug]

    steps:

    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
      
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      timeout-minutes: 4
      continue-on-error: true
      run: msbuild /m /p:Configuration=${{ matrix.configuration }} ${{env.SOLUTION_FILE_PATH}}  # Используем конфигурацию из матрицы
    
    - name: zip
      run: 7z a bin-${{ matrix.configuration }}.zip bin\\${{ matrix.configuration }}-x64\\*

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact-${{ matrix.configuration }}  # Артефакт с указанием конфигурации
        path: bin-${{ matrix.configuration }}.zip

