name: MSBuild

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  SOLUTION_FILE_PATH: ./Liesofp_dlc.sln
  tag1: V${{ github.run_number }}
  BUILD_ID: ${{ github.run_id }}  # Уникальный идентификатор для сборки

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release, Debug]
        platform: [x64]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: |
        msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} ${{env.SOLUTION_FILE_PATH}}

    - name: Zip build artifacts
      run: |
        7z a bin-${{ matrix.configuration }}-${{ matrix.platform }}.zip ${{ github.workspace }}\bin\${{ matrix.configuration }}-${{ matrix.platform }}\*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifact-${{ matrix.configuration }}-${{ matrix.platform }}
        path: bin-${{ matrix.configuration }}-${{ matrix.platform }}.zip

  # Опционально: публикация релиза
  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Download a Build Artifact
  #       uses: actions/download-artifact@v3.0.0
  #       with:
  #         name: my-artifact
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         tag_name: ${{ env.tag1 }}
  #         files: bin-${{ matrix.configuration }}-${{ env.BUILD_ID }}.zip
